# fly.toml app configuration file generated for flash on 2024-09-16T01:39:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flash'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  FASTIFY_ADDRESS = '0.0.0.0'
  PORT = 3000
  DATABASE_URL = 'file:/data/prod.db'
